version: "3.9"

networks:
  net:
    driver: bridge

volumes:
  postgres_db:

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=jblm
    ports:
      - "5432:5432"
    networks:
      - net 
  juke-box-live-music-frontend:
    build:
      context: ./app
      target: frontend
    restart: always
    command: sh -c "pnpm dev --host"
    volumes:
      - ./app/frontend/src/:/app/src/
    ports:
      - "5173:5173"
    networks:
      - net
  juke-box-live-music-backend:
    build:
      context: ./app
      target: backend
    restart: always
    command: sh -c "nodemon -L --ext '*' src/index.js"
    volumes:
      - ./app/server/src/:/app/src/
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database/jblm
      - JWT_SECRET_KEY=XyZ3478sG9kq3S6v9YsAv5THJNu3274v
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - net
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - net